#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-ipset-soname10
Version  : 6.34
Release  : 3
URL      : http://ipset.netfilter.org/ipset-6.34.tar.bz2
Source0  : http://ipset.netfilter.org/ipset-6.34.tar.bz2
Summary  : Userspace library for the ipset extensions and the kernel interface
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: compat-ipset-soname10-bin
Requires: compat-ipset-soname10-lib
Requires: compat-ipset-soname10-doc
BuildRequires : grep
BuildRequires : pkgconfig(libmnl)

%description
This is the ipset source tree. Follow the next steps to install ipset.
If you upgrade from an earlier 5.x release, please read the UPGRADE
instructions too.

%package bin
Summary: bin components for the compat-ipset-soname10 package.
Group: Binaries

%description bin
bin components for the compat-ipset-soname10 package.


%package dev
Summary: dev components for the compat-ipset-soname10 package.
Group: Development
Requires: compat-ipset-soname10-lib
Requires: compat-ipset-soname10-bin
Provides: compat-ipset-soname10-devel

%description dev
dev components for the compat-ipset-soname10 package.


%package doc
Summary: doc components for the compat-ipset-soname10 package.
Group: Documentation

%description doc
doc components for the compat-ipset-soname10 package.


%package lib
Summary: lib components for the compat-ipset-soname10 package.
Group: Libraries

%description lib
lib components for the compat-ipset-soname10 package.


%prep
%setup -q -n ipset-6.34

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523398742
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
%configure --disable-static --with-kmod=no
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1523398742
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/ipset

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/libipset/data.h
%exclude /usr/include/libipset/errcode.h
%exclude /usr/include/libipset/linux_ip_set.h
%exclude /usr/include/libipset/linux_ip_set_bitmap.h
%exclude /usr/include/libipset/linux_ip_set_hash.h
%exclude /usr/include/libipset/linux_ip_set_list.h
%exclude /usr/include/libipset/mnl.h
%exclude /usr/include/libipset/nf_inet_addr.h
%exclude /usr/include/libipset/nfproto.h
%exclude /usr/include/libipset/parse.h
%exclude /usr/include/libipset/pfxlen.h
%exclude /usr/include/libipset/print.h
%exclude /usr/include/libipset/session.h
%exclude /usr/include/libipset/transport.h
%exclude /usr/include/libipset/types.h
%exclude /usr/include/libipset/ui.h
%exclude /usr/include/libipset/utils.h
%exclude /usr/lib64/libipset.so
%exclude /usr/lib64/pkgconfig/libipset.pc

%files doc
%defattr(-,root,root,-)
%exclude /usr/share/man/man8/ipset.8

%files lib
%defattr(-,root,root,-)
/usr/lib64/libipset.so.3
/usr/lib64/libipset.so.3.7.0
